server:
  port: 8888

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/course
    username: root
    password: happy666

mybatis:
  type-aliases-package: com.happy.model
  mapper-locations:
    - mapper/*